// Extract the sheet's SKILL_DATA (attrs + sunsign mods) + SKILL_OML (OML multipliers) into
// chargen/skills.json, so the generator computes Skill Base / OML EXACTLY like harnsheet.html.
// Re-run if the sheet's skill table changes. Run from HarnMaster3/:
//   cmd.exe /c "node chargen\\tools\\extract-skills.mjs"
import { readFileSync, writeFileSync } from 'node:fs';

const html = readFileSync('harnsheet.html', 'utf8');

// Grab a balanced {...} literal that follows a marker, and eval it (JS object literal, not JSON).
function grabObject(marker) {
  const start = html.indexOf(marker);
  if (start < 0) throw new Error(`marker not found: ${marker}`);
  const open = html.indexOf('{', start);
  let depth = 0, i = open;
  for (; i < html.length; i++) {
    if (html[i] === '{') depth++;
    else if (html[i] === '}') { depth--; if (depth === 0) { i++; break; } }
  }
  // eslint-disable-next-line no-eval
  return eval('(' + html.slice(open, i) + ')');
}

const SKILL_DATA = grabObject('const SKILL_DATA =');
const SKILL_OML = grabObject('const SKILL_OML=');

// Capture each skill's group from the `// physical` / `// combat` … comment markers in the
// SKILL_DATA block (drives which repeating section a skill routes to on the sheet).
const sectionFor = (g) => g.startsWith('physical') ? 'physicalskill' : g.startsWith('communication') ? 'communicationskill'
  : g.startsWith('combat') ? 'combatskill' : g.startsWith('ritual') ? 'ritualskill' : 'loreskill';
const blockStart = html.indexOf('const SKILL_DATA =');
const blockEnd = html.indexOf('\n};', blockStart);
const group = {};
let cur = null;
for (const line of html.slice(blockStart, blockEnd).split('\n')) {
  const c = line.match(/^\s*\/\/\s*(.+?)\s*$/);
  if (c) { cur = c[1].toLowerCase(); continue; }
  const k = line.match(/^\s*(?:'([^']+)'|"([^"]+)"|([a-z][\w-]*))\s*:\s*\{/i);
  if (k && cur) group[(k[1] || k[2] || k[3])] = cur;
}

const skills = {};
for (const [k, d] of Object.entries(SKILL_DATA)) {
  skills[k] = { attrs: d.attrs, sun: d.sun || '' };
  if (SKILL_OML[k] != null) skills[k].oml = SKILL_OML[k];
  if (group[k]) { skills[k].group = group[k]; skills[k].section = sectionFor(group[k]); }
}

const out = {
  _meta: {
    harnskills: 1, layer: 'public', source: '4001',
    note: 'PUBLIC skill definitions — extracted from harnsheet.html SKILL_DATA + SKILL_OML (4001 Skill Data table, Skills 3-4). `attrs` = the 3 attributes averaged for Skill Base; `sun` = sunsign-bonus spec (parsed at runtime); `oml` = OML multiplier (ML = SB × oml; absent for Language/Script whose OML is not a simple SB×N). Generated by chargen/tools/extract-skills.mjs — re-run if the sheet changes. A future homebrew/supplement skill layer would merge on top via merge-util.',
  },
  skills,
};
writeFileSync('chargen/skills.json', JSON.stringify(out, null, 2) + '\n');
console.log(`skills.json: ${Object.keys(skills).length} skills (${Object.values(skills).filter((s) => s.oml != null).length} with oml)`);
